-- AlterTable
ALTER TABLE `Inputs` MODIFY `type` ENUM('TEXT', 'NUMBER', 'EMAIL', 'TEL', 'URL', 'PASSWORD', 'FILE', 'CHECKBOX', 'RADIO', 'DATE', 'TIME', 'DATETIME', 'MONTH', 'WEEK', 'COLOR', 'RANGE') NULL;
